In [4]:
import pandas as pd
import numpy as np

In [5]:
# Series
s = pd.Series([21,19,20])

# Access using index (Position)
print(s[0])

# Giving custom index (named Index)
s= pd.Series([21,19,20],index = ["Aryan","Nitin","Sneha"])

# Access using named index
print(s["Sneha"])

# Access using iloc for position index
print(s.iloc[0]) # Single Value
print(s.iloc[[0,1]]) # Multiple Value

# Access using loc for the custom index
print(s.loc["Sneha"]) # Single Label
print(s.loc[["Aryan","Sneha"]]) # Multiple Label

# To print all indexes
print(s.index)

21
20
21
Aryan    21
Nitin    19
dtype: int64
20
Aryan    21
Sneha    20
dtype: int64
Index(['Aryan', 'Nitin', 'Sneha'], dtype='object')

In [6]:
# Properties of Series

# Homogenous - it keeps the data of same data type
s = pd.Series([24,25,26,27,"Aryan"])
print(s)

# Vectorized Operation - can use multiple operations on Series without using loops
s1 = pd.Series([5,6,7,8])
s2 = pd.Series([10,20,30,40])
sum_series = s1 + s2
print(sum_series)

# Handles missing values using NaN - it handles missing values using NaN

# mutable values - can change the values of Series
s = pd.Series([24,25,26])
s[0] = 99
print(s)

# Immutable size - cannot change the size of the Series

s = pd.Series([24,25,16,12])
changed_series = s.drop(0)
print(s)
print(changed_series)

0       24
1       25
2       26
3       27
4    Aryan
dtype: object
0    15
1    26
2    37
3    48
dtype: int64
0    99
1    25
2    26
dtype: int64
0    24
1    25
2    16
3    12
dtype: int64
1    25
2    16
3    12
dtype: int64

In [7]:
# DataFrame Creation

# Using Dictionary
info = {
    "Name":["Aryan","Sneha"],
    "age":[21,20],
}
df = pd.DataFrame(info)
print(df)
# To access row 
print(df.index)
# To access columns
print(df.columns)

# Using List of List
df_list = [["Aryan","Nitin","Sneha"],[21,19,20],[9.6,9.2,9.9]]
df = pd.DataFrame(df_list,columns=["Name","age","cgpa"])
print(df)

# Using np.arrays
np_arr = np.array([["Aryan","Nitin","Sneha"],[21,19,20],[9.6,9.2,9.9]])
df = pd.DataFrame(np_arr,columns = ["Name","age","cgpa"])
print(df)

    Name  age
0  Aryan   21
1  Sneha   20
RangeIndex(start=0, stop=2, step=1)
Index(['Name', 'age'], dtype='object')
    Name    age   cgpa
0  Aryan  Nitin  Sneha
1     21     19     20
2    9.6    9.2    9.9
    Name    age   cgpa
0  Aryan  Nitin  Sneha
1     21     19     20
2    9.6    9.2    9.9

In [8]:
# To read data from different format of files using pandas

# For csv(comma-seperated values) format file
df = pd.read_csv("employee_data.csv")
print(df)

# For json(JavaScript Object Notation) format file
df = pd.read_json("employee_data.json")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [10]:
# Operations on DataFromes 

# Head : To get the first five entries of the top of the data as default or can specify number
df.head()
df.head(6)

# Tail : To get the Last five entries of the last of the data as default or can specify number
df.tail()
df.tail(10)

# Sample : To get the random number of entries from the data 
df.sample()
df.sample(4)

# Info : To get the information about the DataFrame
df.info()

# Shape : To get the dimension of the DataFrame (rows,columns)
df.shape

# Describe : To do the numerical data from the given DataFrame
df.describe()

# columns : To get all columns
df.columns

# nunique : To get n unique values from the DataFrame
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [27]:
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [66]:
# Selecting and Indexing Data

# Columns
df[["country","aqi"]]

# Rows
#Using loc (for the labelled index)
df.loc[22]
df.loc[0:2] # Ending index is inclusive

#Using iloc (for position index)
df.loc[1]
df.iloc[0:2] # Ending index is exclusive

# Selecting rows and columns together
#Using loc (for the labelled index)
df.loc[0:2,["country","city","aqi"]] # Ending index is inclusive

#Using iloc (for position index)
df.iloc[0:2,2:4] # Ending index is exclusive


# Single scalar value

# Using at (for the labelled index)
df.at[0,"city"]

#Using iat (for the position index)
df.iat[0,2]

'New York'

In [99]:
# Filtering (Searching data based on the conditions)

df[df["aqi"] > 100]
df[(df["aqi"] > 100)  & (df["city"] == "Delhi")]

filtered_data = df[(df["aqi"] > 100)  & (df["city"] == "Delhi")][["city","country"]]
filtered_data.iloc[0]

city       Delhi
country       IN
Name: 6841, dtype: object

In [107]:
# Query Method (always return copy of data)
df.query("aqi > 100  & temperature > 30")

# to use attribute use @
city = "Delhi"
df.query("aqi > 100 & city == @city ")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6841,2025-11-04 19:25:17.554219,IN,Delhi,28.704,77.102,38.797,54.046,53.594,3.407,40.532,0.454,133,23.468,30.788,2.936
6842,2025-11-04 20:25:17.554219,IN,Delhi,28.704,77.102,54.364,131.193,34.506,3.664,48.325,1.211,131,16.154,55.117,2.934
6844,2025-11-04 22:25:17.554219,IN,Delhi,28.704,77.102,18.285,54.259,43.646,6.036,47.786,0.409,109,37.776,55.852,6.343
6846,2025-11-05 00:25:17.554219,IN,Delhi,28.704,77.102,44.197,52.547,49.678,3.790,38.681,0.716,124,19.959,38.100,2.399
6848,2025-11-05 02:25:17.554219,IN,Delhi,28.704,77.102,55.419,71.821,25.697,9.105,28.735,0.854,110,19.464,87.713,6.822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7189,2025-11-19 07:25:17.554219,IN,Delhi,28.704,77.102,68.489,93.276,28.489,3.812,56.915,1.275,136,19.881,60.224,0.600
7193,2025-11-19 11:25:17.554219,IN,Delhi,28.704,77.102,35.366,48.881,42.376,4.024,43.475,0.931,105,23.226,42.734,2.272
7195,2025-11-19 13:25:17.554219,IN,Delhi,28.704,77.102,16.101,19.223,57.290,7.124,63.720,0.568,143,11.819,80.977,4.030
7198,2025-11-19 16:25:17.554219,IN,Delhi,28.704,77.102,77.418,121.415,0.139,7.561,47.000,0.845,154,27.715,80.107,7.530
7199,2025-11-19 17:25:17.554219,IN,Delhi,28.704,77.102,62.481,87.965,13.657,2.311,63.675,0.800,124,12.333,86.384,1.656

In [145]:
# Data Handling 
df = pd.read_csv("raw_data.csv")

# Handling Missing Values

# isnull() and isna() :- To check whether the values are null or not ( na = not available)
df.isnull()
df.isna()

# isnull.sum() :- To check the number of missing values in each column
df.isnull().sum()

# dropna() :- To remove missing rows
df.dropna()

# fillna(value) :- To fill the missing value with a value

cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()

cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)
cleaned_data

# forward fill
df.ffill()

# backward fill
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [158]:
# Handling duplicate values

# To find duplicates
df["name"].duplicated()

df2 = df.copy()

# To remove duplicates
df.drop_duplicates()
df.drop_duplicates(inplace = True) # To make changes in the original data frame
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [189]:
# Data tupes 

df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64") # To change the data types of a perticular column
df2.dtypes # To check the data types of each columns

# to_datatime(date ) 
s = pd.Series([pd.to_datetime("2026-06-30")])
type(s.dtypes)

numpy.dtypes.DateTime64DType

In [194]:
# Handling Strings

# To make lower case
df2["country"] = df2["country"].str.lower()

# To make Upper case
df2["country"] = df2["country"].str.upper()

# To split
df2["name"].str.split(" ")

# To check whether value exists or not . also it allow case insensitive
df2["name"].str.contains("alex",case = False)

0     False
2     False
3      True
4     False
5     False
6       NaN
7     False
8     False
9     False
10    False
Name: name, dtype: object

In [192]:

df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  CANADA   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   SPAIN   Female      0.0
5    5        Li Wei   27   CHINA     Male  51000.0
6    6             0   45   INDIA   Female  73000.0
7    7    Ahmed Khan   38     NaN     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  MEXICO     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0